name: sbx_deployment
on:
  push:
    branches:
      - main
jobs:
  build_bsc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build BSC
        run: yarn build
        env:
          REACT_APP_BLOCKS_API: ${{ secrets.REACT_APP_BLOCKS_API_BSC_SBX }}
          REACT_APP_SCAN_URL: ${{ secrets.REACT_APP_SCAN_URL_BSC_SBX }}
          REACT_APP_TOKEN_AUTH: ${{ secrets.REACT_APP_TOKEN_AUTH_BSC_SBX }}
          REACT_APP_FOREIGN_CHAIN_ID: ${{ secrets.REACT_APP_FOREIGN_CHAIN_ID_BSC_SBX }}

      - name: Upload environment to be used by the next job
        uses: actions/upload-artifact@v2
        with:
          name: build_bsc
          path: build
          retention-days: 1
  
  build_eth:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build ETH
        run: yarn build
        env:
          REACT_APP_BLOCKS_API: ${{ secrets.REACT_APP_BLOCKS_API_ETH_SBX }}
          REACT_APP_SCAN_URL: ${{ secrets.REACT_APP_SCAN_URL_ETH_SBX }}
          REACT_APP_TOKEN_AUTH: ${{ secrets.REACT_APP_TOKEN_AUTH_ETH_SBX }}
          REACT_APP_FOREIGN_CHAIN_ID: ${{ secrets.REACT_APP_FOREIGN_CHAIN_ID_ETH_SBX }}

      - name: Upload environment to be used by the next job
        uses: actions/upload-artifact@v2
        with:
          name: build_eth
          path: build
          retention-days: 1
  
  build_polygon:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build polygon
        run: yarn build
        env:
          REACT_APP_BLOCKS_API: ${{ secrets.REACT_APP_BLOCKS_API_POLYGON_SBX }}
          REACT_APP_SCAN_URL: ${{ secrets.REACT_APP_SCAN_URL_POLYGON_SBX }}
          REACT_APP_TOKEN_AUTH: ${{ secrets.REACT_APP_TOKEN_AUTH_POLYGON_SBX }}
          REACT_APP_FOREIGN_CHAIN_ID: ${{ secrets.REACT_APP_FOREIGN_CHAIN_ID_POLYGON_SBX }}

      - name: Upload environment to be used by the next job
        uses: actions/upload-artifact@v2
        with:
          name: build_polygon
          path: build
          retention-days: 1

  build_avalanche:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build avalanche
        run: yarn build
        env:
          REACT_APP_BLOCKS_API: ${{ secrets.REACT_APP_BLOCKS_API_AVALANCHE_SBX }}
          REACT_APP_SCAN_URL: ${{ secrets.REACT_APP_SCAN_URL_AVALANCHE_SBX }}
          REACT_APP_TOKEN_AUTH: ${{ secrets.REACT_APP_TOKEN_AUTH_AVALANCHE_SBX }}
          REACT_APP_FOREIGN_CHAIN_ID: ${{ secrets.REACT_APP_FOREIGN_CHAIN_ID_AVALANCHE_SBX }}

      - name: Upload environment to be used by the next job
        uses: actions/upload-artifact@v2
        with:
          name: build_avalanche
          path: build
          retention-days: 1
  
  build_arbitrum:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build arbitrum
        run: yarn build
        env:
          REACT_APP_BLOCKS_API: ${{ secrets.REACT_APP_BLOCKS_API_ARBITRUM_SBX }}
          REACT_APP_SCAN_URL: ${{ secrets.REACT_APP_SCAN_URL_ARBITRUM_SBX }}
          REACT_APP_TOKEN_AUTH: ${{ secrets.REACT_APP_TOKEN_AUTH_ARBITRUM_SBX }}
          REACT_APP_FOREIGN_CHAIN_ID: ${{ secrets.REACT_APP_FOREIGN_CHAIN_ID_ARBITRUM_SBX }}

      - name: Upload environment to be used by the next job
        uses: actions/upload-artifact@v2
        with:
          name: build_arbitrum
          path: build
          retention-days: 1

  push_bsc_sbx:
    needs: build_bsc
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build_bsc
          path: build-download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync build-download/ s3://${{ secrets.AWS_S3_BUCKET_SBX }} --cache-control "max-age=86400" --delete --only-show-errors
          aws s3 cp build-download/index.html s3://${{ secrets.AWS_S3_BUCKET_SBX }} --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_SBX }}
  
  push_eth_sbx:
    needs: build_eth
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build_eth
          path: build-download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync build-download/ s3://${{ secrets.AWS_S3_BUCKET_ETH_SBX }} --cache-control "max-age=86400" --delete --only-show-errors
          aws s3 cp build-download/index.html s3://${{ secrets.AWS_S3_BUCKET_ETH_SBX }} --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_ETH_SBX }}

  push_polygon_sbx:
    needs: build_polygon
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build_polygon
          path: build-download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync build-download/ s3://${{ secrets.AWS_S3_BUCKET_POLYGON_SBX }} --cache-control "max-age=86400" --delete --only-show-errors
          aws s3 cp build-download/index.html s3://${{ secrets.AWS_S3_BUCKET_POLYGON_SBX }} --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_POLYGON_SBX }}
  
  push_avalanche_sbx:
    needs: build_avalanche
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build_avalanche
          path: build-download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync build-download/ s3://${{ secrets.AWS_S3_BUCKET_AVALANCHE_SBX }} --cache-control "max-age=86400" --delete --only-show-errors
          aws s3 cp build-download/index.html s3://${{ secrets.AWS_S3_BUCKET_AVALANCHE_SBX }} --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_AVALANCHE_SBX }}
  
  push_arbitrum_sbx:
    needs: build_arbitrum
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build_arbitrum
          path: build-download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync build-download/ s3://${{ secrets.AWS_S3_BUCKET_ARBITRUM_SBX }} --cache-control "max-age=86400" --delete --only-show-errors
          aws s3 cp build-download/index.html s3://${{ secrets.AWS_S3_BUCKET_ARBITRUM_SBX }} --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_ARBITRUM_SBX }}
